### ISSUE TITLE
Cannot specify "SÆSON" when retrieving data

### ISSUE THREAD

**Issue by mathildebechmann** [mikkelkrogsholm/statsDK#1]
I'm encountering the following problem, when I  specify seasonal adjustment in a data series. It seems like R isn't able to read the "Æ" in "SÆSON"? 

![image](https://user-images.githubusercontent.com/49937788/56960134-1bd4d700-6b50-11e9-8c83-1679bc70188f.png)

If I continue with the last bit, where data is collected succesfully, I keep running into problem - always because of the "Æ" in "SÆSON"

**Comment by mikkelkrogsholm** [comment]
Can you provide the output from "sessionInfo()" ?

**Comment by mathildebechmann** [comment]
![image](https://user-images.githubusercontent.com/49937788/56961076-0ca35880-6b53-11e9-83c5-dbe4ec44f397.png)

**Comment by mikkelkrogsholm** [comment]
I just ran the code myself:

library(statsDK)
bb1s <- retrieve_data(table_id = "BB1S",
                      Tid = "*",
                      POST = "*",
                      INDUDBOP = "*",
                      SÆSON = "2",
                      LAND = "w1",
                      lang = "dk")

It works. It is most likely because I am on linux. Windows often has a lot of encoding issues when it comes to using danish and R.

I do not have a windows machine, so I cannot fix the issue for you. Sorry.

**Comment by dzgreen** [comment]
I encountered the same issue on a windows machine, but no problem on a linux machine. You can get around the problem by just removing the line with a danish letter, and then filtering the data frame. 

This fails with the error: 

> Values must be selected for variable: OMRÅDE 

`regk100 <- sdk_retrieve_data(table_id = "REGK100",
                             ART = "TOT",
                             DRANST = "1",
                             EJER = "*",
                             FUNKTION = funktion_input,
                             GRUPPERING = "*",
                             OMRÅDE = "*",
                             Tid = "*")`

If I remove the OMRÅDE argument, it works fine, with the message:

> Autosetting missing values to * for: OMRÅDE

So it seems like there is a problem when the argument has a Danish letter, as was also the case with @mathildebechmann 's example.  

Btw Thanks for a great package.
