### ISSUE TITLE
Package removed by CRAN

### ISSUE THREAD

**Issue by robabsmith** [mikkelkrogsholm/statsDK#2]
Hi Mikkel, firstly thank you very much for making an excellent package available. Unfortunately CRAN removed your package from the repository on the 29th Sept, and I was wondering if you are considering resolving the error checks that were raised and reinstating it?

**Comment by mikkelkrogsholm** [comment]
Hi, Rob, yes Ill have a look at it
:)

**Comment by mikkelkrogsholm** [comment]
Package has been updated and re-submitted to CRAN. Fingers crossed :)

**Comment by robabsmith** [comment]
Hi Mikkel, thanks so much for such a quick response. Just wanted to use it for teaching some students in Aalborg today, so here's to hoping it goes through to the repository speedily. The devtools install still works perfectly well, it'll just be great to have it back in the available packages :)
Thanks also for such a quick turn around in taking a look at the package. It's truly appreciated.

**Comment by mikkelkrogsholm** [comment]
So, my examples took too long to run, so I had to re-submit again. Please note also that there are breaking changes in the syntax: all functions now have sdk_ in front of them.
